### ISSUE TITLE
ContainerEvents currentEvent not handling undefined case

### ISSUE THREAD

**Issue by cpritcha** [virtualcommons/port-of-mars#169]
Running

```bash
./configure dev
make test
```

results in

```
docker-compose run --rm client yarn test:unit
yarn run v1.21.1
$ vue-cli-service test:unit
 PASS  tests/unit/app.spec.ts
 PASS  tests/unit/tutorial.spec.ts (5.251s)
  ● Console

    console.error node_modules/vue/dist/vue.runtime.common.dev.js:621
      [Vue warn]: Error in render: "TypeError: Cannot read property 'id' of undefined"
      
      found in
      
      ---> <ContainerEvents>
             <ContainerBottom>
               <ContainerBoard>
                 <GameDashboard>
                   <Tutorial>
                     <Root>
    console.error node_modules/vue/dist/vue.runtime.common.dev.js:1884
      TypeError: Cannot read property 'id' of undefined
          at VueComponent.get currentEvent (/code/client/src/components/gamedashboard/bottom/containers/ContainerEvents.vue:49:1)
          at Watcher.get (/code/client/node_modules/vue/dist/vue.runtime.common.dev.js:4465:25)
          at Watcher.evaluate (/code/client/node_modules/vue/dist/vue.runtime.common.dev.js:4570:21)
          at VueComponent.computedGetter [as currentEvent] (/code/client/node_modules/vue/dist/vue.runtime.common.dev.js:4819:17)
          at VueComponent.get currentEventName (/code/client/src/components/gamedashboard/bottom/containers/ContainerEvents.vue:61:1)
          at Watcher.get (/code/client/node_modules/vue/dist/vue.runtime.common.dev.js:4465:25)
          at Watcher.evaluate (/code/client/node_modules/vue/dist/vue.runtime.common.dev.js:4570:21)
          at Proxy.computedGetter (/code/client/node_modules/vue/dist/vue.runtime.common.dev.js:4819:17)
          at Proxy.render (/code/client/src/components/gamedashboard/bottom/containers/ContainerEvents.vue:65:483)
          at VueComponent.Vue._render (/code/client/node_modules/vue/dist/vue.runtime.common.dev.js:3538:22)
          at VueComponent.updateComponent (/code/client/node_modules/vue/dist/vue.runtime.common.dev.js:4054:21)
          at Watcher.get (/code/client/node_modules/vue/dist/vue.runtime.common.dev.js:4465:25)
          at new Watcher (/code/client/node_modules/vue/dist/vue.runtime.common.dev.js:4454:12)
          at mountComponent (/code/client/node_modules/vue/dist/vue.runtime.common.dev.js:4061:3)
          at VueComponent.Object.<anonymous>.Vue.$mount (/code/client/node_modules/vue/dist/vue.runtime.common.dev.js:8392:10)
          at init (/code/client/node_modules/vue/dist/vue.runtime.common.dev.js:3112:13)
          at createComponent (/code/client/node_modules/vue/dist/vue.runtime.common.dev.js:5958:9)
          at createElm (/code/client/node_modules/vue/dist/vue.runtime.common.dev.js:5905:9)
          at updateChildren (/code/client/node_modules/vue/dist/vue.runtime.common.dev.js:6196:11)
          at patchVnode (/code/client/node_modules/vue/dist/vue.runtime.common.dev.js:6299:29)
          at updateChildren (/code/client/node_modules/vue/dist/vue.runtime.common.dev.js:6173:9)
          at patchVnode (/code/client/node_modules/vue/dist/vue.runtime.common.dev.js:6299:29)
          at updateChildren (/code/client/node_modules/vue/dist/vue.runtime.common.dev.js:6173:9)
          at patchVnode (/code/client/node_modules/vue/dist/vue.runtime.common.dev.js:6299:29)
          at VueComponent.patch [as __patch__] (/code/client/node_modules/vue/dist/vue.runtime.common.dev.js:6460:9)
          at VueComponent.Vue._update (/code/client/node_modules/vue/dist/vue.runtime.common.dev.js:3936:19)
          at VueComponent.updateComponent (/code/client/node_modules/vue/dist/vue.runtime.common.dev.js:4054:10)
          at Watcher.get (/code/client/node_modules/vue/dist/vue.runtime.common.dev.js:4465:25)
          at Watcher.run (/code/client/node_modules/vue/dist/vue.runtime.common.dev.js:4540:22)
          at flushSchedulerQueue (/code/client/node_modules/vue/dist/vue.runtime.common.dev.js:4298:13)
          at Array.<anonymous> (/code/client/node_modules/vue/dist/vue.runtime.common.dev.js:1976:12)
          at flushCallbacks (/code/client/node_modules/vue/dist/vue.runtime.common.dev.js:1902:14)
          at processTicksAndRejections (internal/process/task_queues.js:94:5)
    console.error node_modules/vue/dist/vue.runtime.common.dev.js:621
      [Vue warn]: Error in render: "TypeError: Cannot read property 'id' of undefined"
      
      found in
      
      ---> <ContainerEvents>
             <ContainerBottom>
               <ContainerBoard>
                 <GameDashboard>
                   <Tutorial>
                     <Root>
    console.error node_modules/vue/dist/vue.runtime.common.dev.js:1884
      TypeError: Cannot read property 'id' of undefined
          at VueComponent.get currentEvent (/code/client/src/components/gamedashboard/bottom/containers/ContainerEvents.vue:49:1)
          at Watcher.get (/code/client/node_modules/vue/dist/vue.runtime.common.dev.js:4465:25)
          at Watcher.evaluate (/code/client/node_modules/vue/dist/vue.runtime.common.dev.js:4570:21)
          at VueComponent.computedGetter [as currentEvent] (/code/client/node_modules/vue/dist/vue.runtime.common.dev.js:4819:17)
          at VueComponent.get currentEventName (/code/client/src/components/gamedashboard/bottom/containers/ContainerEvents.vue:61:1)
          at Watcher.get (/code/client/node_modules/vue/dist/vue.runtime.common.dev.js:4465:25)
          at Watcher.evaluate (/code/client/node_modules/vue/dist/vue.runtime.common.dev.js:4570:21)
          at Proxy.computedGetter (/code/client/node_modules/vue/dist/vue.runtime.common.dev.js:4819:17)
          at Proxy.render (/code/client/src/components/gamedashboard/bottom/containers/ContainerEvents.vue:65:483)
          at VueComponent.Vue._render (/code/client/node_modules/vue/dist/vue.runtime.common.dev.js:3538:22)
          at VueComponent.updateComponent (/code/client/node_modules/vue/dist/vue.runtime.common.dev.js:4054:21)
          at Watcher.get (/code/client/node_modules/vue/dist/vue.runtime.common.dev.js:4465:25)
          at Watcher.run (/code/client/node_modules/vue/dist/vue.runtime.common.dev.js:4540:22)
          at flushSchedulerQueue (/code/client/node_modules/vue/dist/vue.runtime.common.dev.js:4298:13)
          at Array.<anonymous> (/code/client/node_modules/vue/dist/vue.runtime.common.dev.js:1976:12)
          at flushCallbacks (/code/client/node_modules/vue/dist/vue.runtime.common.dev.js:1902:14)
          at processTicksAndRejections (internal/process/task_queues.js:94:5)
    console.error node_modules/vue/dist/vue.runtime.common.dev.js:621
      [Vue warn]: Error in render: "TypeError: Cannot read property 'id' of undefined"
      
      found in
      
      ---> <ContainerEvents>
             <ContainerBottom>
               <ContainerBoard>
                 <GameDashboard>
                   <Tutorial>
                     <Root>
    console.error node_modules/vue/dist/vue.runtime.common.dev.js:1884
      TypeError: Cannot read property 'id' of undefined
          at VueComponent.get currentEvent (/code/client/src/components/gamedashboard/bottom/containers/ContainerEvents.vue:49:1)
          at Watcher.get (/code/client/node_modules/vue/dist/vue.runtime.common.dev.js:4465:25)
          at Watcher.evaluate (/code/client/node_modules/vue/dist/vue.runtime.common.dev.js:4570:21)
          at VueComponent.computedGetter [as currentEvent] (/code/client/node_modules/vue/dist/vue.runtime.common.dev.js:4819:17)
          at VueComponent.get currentEventName (/code/client/src/components/gamedashboard/bottom/containers/ContainerEvents.vue:61:1)
          at Watcher.get (/code/client/node_modules/vue/dist/vue.runtime.common.dev.js:4465:25)
          at Watcher.evaluate (/code/client/node_modules/vue/dist/vue.runtime.common.dev.js:4570:21)
          at Proxy.computedGetter (/code/client/node_modules/vue/dist/vue.runtime.common.dev.js:4819:17)
          at Proxy.render (/code/client/src/components/gamedashboard/bottom/containers/ContainerEvents.vue:65:483)
          at VueComponent.Vue._render (/code/client/node_modules/vue/dist/vue.runtime.common.dev.js:3538:22)
          at VueComponent.updateComponent (/code/client/node_modules/vue/dist/vue.runtime.common.dev.js:4054:21)
          at Watcher.get (/code/client/node_modules/vue/dist/vue.runtime.common.dev.js:4465:25)
          at Watcher.run (/code/client/node_modules/vue/dist/vue.runtime.common.dev.js:4540:22)
          at flushSchedulerQueue (/code/client/node_modules/vue/dist/vue.runtime.common.dev.js:4298:13)
          at Array.<anonymous> (/code/client/node_modules/vue/dist/vue.runtime.common.dev.js:1976:12)
          at flushCallbacks (/code/client/node_modules/vue/dist/vue.runtime.common.dev.js:1902:14)
          at processTicksAndRejections (internal/process/task_queues.js:94:5)
    console.error node_modules/vue/dist/vue.runtime.common.dev.js:621
      [Vue warn]: Error in render: "TypeError: Cannot read property 'id' of undefined"
      
      found in
      
      ---> <ContainerEvents>
             <ContainerBottom>
               <ContainerBoard>
                 <GameDashboard>
                   <Tutorial>
                     <Root>
    console.error node_modules/vue/dist/vue.runtime.common.dev.js:1884
      TypeError: Cannot read property 'id' of undefined
          at VueComponent.get currentEvent (/code/client/src/components/gamedashboard/bottom/containers/ContainerEvents.vue:49:1)
          at Watcher.get (/code/client/node_modules/vue/dist/vue.runtime.common.dev.js:4465:25)
          at Watcher.evaluate (/code/client/node_modules/vue/dist/vue.runtime.common.dev.js:4570:21)
          at VueComponent.computedGetter [as currentEvent] (/code/client/node_modules/vue/dist/vue.runtime.common.dev.js:4819:17)
          at VueComponent.get currentEventName (/code/client/src/components/gamedashboard/bottom/containers/ContainerEvents.vue:61:1)
          at Watcher.get (/code/client/node_modules/vue/dist/vue.runtime.common.dev.js:4465:25)
          at Watcher.evaluate (/code/client/node_modules/vue/dist/vue.runtime.common.dev.js:4570:21)
          at Proxy.computedGetter (/code/client/node_modules/vue/dist/vue.runtime.common.dev.js:4819:17)
          at Proxy.render (/code/client/src/components/gamedashboard/bottom/containers/ContainerEvents.vue:65:483)
          at VueComponent.Vue._render (/code/client/node_modules/vue/dist/vue.runtime.common.dev.js:3538:22)
          at VueComponent.updateComponent (/code/client/node_modules/vue/dist/vue.runtime.common.dev.js:4054:21)
          at Watcher.get (/code/client/node_modules/vue/dist/vue.runtime.common.dev.js:4465:25)
          at Watcher.run (/code/client/node_modules/vue/dist/vue.runtime.common.dev.js:4540:22)
          at flushSchedulerQueue (/code/client/node_modules/vue/dist/vue.runtime.common.dev.js:4298:13)
          at Array.<anonymous> (/code/client/node_modules/vue/dist/vue.runtime.common.dev.js:1976:12)
          at flushCallbacks (/code/client/node_modules/vue/dist/vue.runtime.common.dev.js:1902:14)
          at processTicksAndRejections (internal/process/task_queues.js:94:5)
    console.error node_modules/vue/dist/vue.runtime.common.dev.js:621
      [Vue warn]: Error in render: "TypeError: Cannot read property 'id' of undefined"
      
      found in
      
      ---> <ContainerEvents>
             <ContainerBottom>
               <ContainerBoard>
                 <GameDashboard>
                   <Tutorial>
                     <Root>
    console.error node_modules/vue/dist/vue.runtime.common.dev.js:1884
      TypeError: Cannot read property 'id' of undefined
          at VueComponent.get currentEvent (/code/client/src/components/gamedashboard/bottom/containers/ContainerEvents.vue:49:1)
          at Watcher.get (/code/client/node_modules/vue/dist/vue.runtime.common.dev.js:4465:25)
          at Watcher.evaluate (/code/client/node_modules/vue/dist/vue.runtime.common.dev.js:4570:21)
          at VueComponent.computedGetter [as currentEvent] (/code/client/node_modules/vue/dist/vue.runtime.common.dev.js:4819:17)
          at VueComponent.get currentEventName (/code/client/src/components/gamedashboard/bottom/containers/ContainerEvents.vue:61:1)
          at Watcher.get (/code/client/node_modules/vue/dist/vue.runtime.common.dev.js:4465:25)
          at Watcher.evaluate (/code/client/node_modules/vue/dist/vue.runtime.common.dev.js:4570:21)
          at Proxy.computedGetter (/code/client/node_modules/vue/dist/vue.runtime.common.dev.js:4819:17)
          at Proxy.render (/code/client/src/components/gamedashboard/bottom/containers/ContainerEvents.vue:65:483)
          at VueComponent.Vue._render (/code/client/node_modules/vue/dist/vue.runtime.common.dev.js:3538:22)
          at VueComponent.updateComponent (/code/client/node_modules/vue/dist/vue.runtime.common.dev.js:4054:21)
          at Watcher.get (/code/client/node_modules/vue/dist/vue.runtime.common.dev.js:4465:25)
          at Watcher.run (/code/client/node_modules/vue/dist/vue.runtime.common.dev.js:4540:22)
          at flushSchedulerQueue (/code/client/node_modules/vue/dist/vue.runtime.common.dev.js:4298:13)
          at Array.<anonymous> (/code/client/node_modules/vue/dist/vue.runtime.common.dev.js:1976:12)
          at flushCallbacks (/code/client/node_modules/vue/dist/vue.runtime.common.dev.js:1902:14)
          at processTicksAndRejections (internal/process/task_queues.js:94:5)
```

**Comment by cpritcha** [comment]
Test was fixed by adding a default event.
