### ISSUE TITLE
New tournament entities crashing server

### ISSUE THREAD

**Issue by lfaivre** [virtualcommons/port-of-mars#279]
Tests passed and build was working before PR. Now getting this error when starting server after adding tournament entities.

````
 QueryFailedError: column "name" contains null values
     at new QueryFailedError (/code/server/src/error/QueryFailedError.ts:9:9)
     at Query.callback (/code/server/src/driver/postgres/PostgresQueryRunner.ts:178:30)
     at Query.handleError (/code/server/node_modules/pg/lib/query.js:145:17)
     at Connection.connectedErrorMessageHandler (/code/server/node_modules/pg/lib/client.js:214:17)
     at Connection.emit (events.js:321:20)
     at Connection.EventEmitter.emit (domain.js:485:12)
     at Socket.<anonymous> (/code/server/node_modules/pg/lib/connection.js:128:12)
     at Socket.emit (events.js:321:20)
     at Socket.EventEmitter.emit (domain.js:485:12)
     at addChunk (_stream_readable.js:297:12) {
   message: 'column "name" contains null values',
   name: 'QueryFailedError',
   length: 123,
   severity: 'ERROR',
   code: '23502',
   detail: undefined,
   hint: undefined,
   position: undefined,
   internalPosition: undefined,
   internalQuery: undefined,
   where: undefined,
   schema: 'public',
   table: 'tournament',
   column: 'name',
   dataType: undefined,
   constraint: undefined,
   file: 'tablecmds.c',
   line: '5054',
   routine: 'ATRewriteTable',
   query: 'ALTER TABLE "tournament" ADD "name" character varying NOT NULL',
   parameters: []
 }
````

**Comment by cpritcha** [comment]
You'll need to drop the database and reload the fixtures. I created a command called 'resetdb' in package.json

**Comment by cpritcha** [comment]
922075d

**Comment by cpritcha** [comment]
we need to change our fixtures to include foreign keys to tournamentRound etc

**Comment by cpritcha** [comment]
I'll put up tournament and tournamentRound fixtures.

**Comment by cpritcha** [comment]
647c733 got it working for me again. you'll need to reset the database

**Comment by cpritcha** [comment]
Fixed
