### ISSUE TITLE
trade crashed server

### ISSUE THREAD

**Issue by alee** [virtualcommons/port-of-mars#373]
```
server_1  | {"level":10,"time":1585346934267,"pid":42,"hostname":"925235ef66da","msg":"prepareRequest from gywv-erdz : {\"r\":{\"kind\":\"accept-trade-request\",\"id\":\"mock-trade-1\"}}","v":1}                               server_1  | TypeError: Cannot read property 'to' of undefined                                                                                                                                                                    
server_1  |     at GameState.acceptTrade (/code/server/src/rooms/game/state/index.js:1067:30)                                                                                                                                    
server_1  |     at AcceptedTradeRequest.apply (/code/server/src/rooms/game/events/index.js:96:14)                                                                                                                                
server_1  |     at /code/server/src/rooms/game/state/index.js:977:30                                                                                                                                                             
server_1  |     at Array.forEach (<anonymous>)                                               
server_1  |     at GameState.applyMany (/code/server/src/rooms/game/state/index.js:977:15)                           
server_1  |     at GameRoom.onMessage (/code/server/src/rooms/game/index.js:129:20)                                                                                                                                             
server_1  |     at GameRoom._onMessage (/code/server/node_modules/colyseus/lib/Room.js:420:18)                                                                                                                                   
server_1  |     at WebSocket.emit (events.js:316:20)                                                                                                                                                                             
server_1  |     at WebSocket.EventEmitter.emit (domain.js:485:12)                                                                                                                                                                
server_1  |     at Receiver.receiverOnMessage (/code/server/node_modules/colyseus/node_modules/ws/lib/websocket.js:801:20)                                                                                                       
server_1  |     at Receiver.emit (events.js:316:20)                                          
server_1  |     at Receiver.EventEmitter.emit (domain.js:485:12)                                                     
server_1  |     at Receiver.dataMessage (/code/server/node_modules/colyseus/node_modules/ws/lib/receiver.js:427:14)                                                                                                             
server_1  |     at Receiver.getData (/code/server/node_modules/colyseus/node_modules/ws/lib/receiver.js:366:17)                                                                                                                  
server_1  |     at Receiver.startLoop (/code/server/node_modules/colyseus/node_modules/ws/lib/receiver.js:142:22)                                                                                                                
server_1  |     at Receiver._write (/code/server/node_modules/colyseus/node_modules/ws/lib/receiver.js:77:10)                   
```

**Comment by alee** [comment]
Disconnected everyone from the room after this occurred

**Comment by alee** [comment]
this was related to the misguided use of vuex-persistedstate to store the client side store. removed in favor of having colyseus do the right thing with state synchronization on reconnect
