### ISSUE TITLE
verify token button generates server exception

### ISSUE THREAD

**Issue by alee** [virtualcommons/port-of-mars#469]
the error message is not getting displayed on the player dashboard either so something in the exception handling / routing still needs to be fixed as well

```
server_1  | {"level":40,"time":1588298001364,"pid":44,"hostname":"e7f604384f3d","filename":"/code/server/src/index.js","code":400,"displayMessage":"Sorry, your registration token does not appear to be valid. Please try to verify your account again and contact us if this continues.","stack":"Error: Invalid registration token undefined\n    at RegistrationService.<anonymous> (/code/server/src/services/registration.js:52:23)\n    at Generator.next (<anonymous>)\n    at /code/server/src/services/registration.js:8:71\n    at new Promise (<anonymous>)\n    at __awaiter (/code/server/src/services/registration.js:4:12)\n    at RegistrationService.verifyUnregisteredUser (/code/server/src/services/registration.js:49:16)\n    at /code/server/src/routes/registration.js:38:53\n    at Generator.next (<anonymous>)\n    at /code/server/src/routes/registration.js:8:71\n    at new Promise (<anonymous>)\n    at __awaiter (/code/server/src/routes/registration.js:4:12)\n    at /code/server/src/routes/registration.js:34:83\n    at Layer.handle [as handle_request] (/code/server/node_modules/express/lib/router/layer.js:95:5)\n    at next (/code/server/node_modules/express/lib/router/route.js:137:13)\n    at Route.dispatch (/code/server/node_modules/express/lib/router/route.js:112:3)\n    at Layer.handle [as handle_request] (/code/server/node_modules/express/lib/router/layer.js:95:5)","type":"Error","msg":"Invalid registration token undefined"}
```

**Comment by alee** [comment]
steps to reproduce:

1. sign in via cas
2. grant consent, fill in name + email
3. click on Verify your email (which shouldn't actually be available in the todo items except for in dev mode since we need them to only get there from the email link)

**Comment by alee** [comment]
it appears the registrationToken is always null on the Verify.vue component and so it's sending an empty token to the server side
