### ISSUE TITLE
local tests consistently fail

### ISSUE THREAD

**Issue by alee** [virtualcommons/port-of-mars#518]
For some reason my local environment always fails `make test`. @chrstngyn and @cpritcha can you verify if this happens on yours as well?

```
FAIL  tests/services/registration.test.ts

● a potential user › can begin registration
    QueryFailedError: duplicate key value violates unique constraint "pg_type_typname_nsp_index"at new QueryFailedError (src/error/QueryFailedError.ts:9:9)
at Query.callback (src/driver/postgres/PostgresQueryRunner.ts:178:30)                                                                                                                                                                  at Query.handleError (node_modules/pg/lib/query.js:146:19)
at Connection.connectedErrorMessageHandler (node_modules/pg/lib/client.js:236:17)
at Socket.<anonymous> (node_modules/pg/lib/connection.js:121:12)

 ● a potential user › can begin registration

TypeError: Cannot read property 'account' of undefined

25 |
26 |   it('can begin registration', async () => {
> 27 |       const u = await sp.account.getOrCreateUser(username);
```

**Comment by chrstngyn** [comment]
just rebuilt my images. `make test` didn't fail for me

**Comment by alee** [comment]
Thanks for confirming! I was pretty sure it was an issue in my local env but wanted to double check.

Cleaning out the old DB appears to have fixed the issue
