### ISSUE TITLE
error during single player game with bots

### ISSUE THREAD

**Issue by alee** [virtualcommons/port-of-mars#521]
```
server_1  | TypeError: Cannot read property 'timeDuration' of undefined                                                                                                                                                                
server_1  |     at ReenteredMarsEventPhase.apply (/code/server/src/rooms/game/events/index.js:210:72)                                                                                                                                  
server_1  |     at /code/server/src/rooms/game/state/index.js:1056:30                                                                                                                                                                  
server_1  |     at Array.forEach (<anonymous>)                                                                                                                                                                                         
server_1  |     at GameState.applyMany (/code/server/src/rooms/game/state/index.js:1056:15)                                                                                                                                            
server_1  |     at Object.* (/code/server/src/rooms/game/index.js:82:28)                                                                                                                                                               
server_1  |     at GameRoom._onMessage (/code/server/node_modules/colyseus/lib/Room.js:446:44)                                                                                                                                         
server_1  |     at WebSocket.emit (events.js:315:20)                                                                                                                                                                                   
server_1  |     at WebSocket.EventEmitter.emit (domain.js:485:12)                                                                                                                                                                      
server_1  |     at Receiver.receiverOnMessage (/code/server/node_modules/ws/lib/websocket.js:800:20)                                                                                                                                   
server_1  |     at Receiver.emit (events.js:315:20)                                                                                                                                                                                    
server_1  |     at Receiver.EventEmitter.emit (domain.js:485:12)                                                                                                                                                                       
server_1  |     at Receiver.dataMessage (/code/server/node_modules/ws/lib/receiver.js:427:14)                                                                                                                                          
server_1  |     at Receiver.getData (/code/server/node_modules/ws/lib/receiver.js:366:17)                                                                                                                                              
server_1  |     at Receiver.startLoop (/code/server/node_modules/ws/lib/receiver.js:142:22)                                                                                                                                            
server_1  |     at Receiver._write (/code/server/node_modules/ws/lib/receiver.js:77:10)                                                                                                                                                
server_1  |     at writeOrBuffer (_stream_writable.js:378:12)                                                                                                                                                                          
server_1  | {"level":30,"time":1590109499069,"pid":41,"hostname":"dcd2e83c3f7d","filename":"/code/server/src/rooms/game/index.js","msg":"Disposing of room"}
server_1  | {"level":20,"time":1590109499069,"pid":41,"hostname":"dcd2e83c3f7d","filename":"/code/server/src/services/persistence.js","msg":"syncing to db"}
server_1  | {"level":20,"time":1590109499114,"pid":41,"hostname":"dcd2e83c3f7d","filename":"/code/server/src/services/persistence.js","msg":"synced to db"}
server_1  | {"level":20,"time":1590109499115,"pid":41,"hostname":"dcd2e83c3f7d","filename":"/code/server/src/services/persistence.js","msg":"finalizing game 31"}
server_1  | onDispose error: Could not find any entity of type "GameEvent" matching: {
server_1  |     "where": {
server_1  |         "type": {
server_1  |             "_type": "in",
server_1  |             "_value": [
server_1  |                 "entered-defeat-phase",
server_1  |                 "entered-victory-phase"
server_1  |             ],
server_1  |             "_useParameter": true,
server_1  |             "_multipleParameters": true
server_1  |         },
server_1  |         "gameId": 31
server_1  |     },
server_1  |     "order": {
server_1  |         "id": "DESC",
server_1  |         "dateCreated": "DESC"
server_1  |     }
```

**Comment by alee** [comment]
I think this is fixed in 6ca2b1125dbfc3e5fdf08020089ef345999dea3f, there was an off-by-one bug in the hasMarsEventsToProcess when I inverted the conditional logic
