### ISSUE TITLE
nuxt 3 typeorm support

### ISSUE THREAD

**Issue by alee** [virtualcommons/port-of-mars#809]
typeorm integration currently failing despite following installation steps from https://github.com/typeorm/typeorm#installation

1. configure `tsconfig.json` with `emitDecoratorMetadata:true` and other recommended settings
2. strangely `yarn build` still works but the dev nitro server fails, so this may be a nitro issue with Decorators

workaround is to explicitly set types on every Column decorator and then see what else breaks

```
port-of-mars-nuxt-1  | [nitro] [dev] [uncaughtException] ColumnTypeUndefinedError: Column type for Tournament#name is not defined and cannot be guessed. Make sure you have turned on an "emitDecoratorMetadata": true option in tsconfig.json. Also make sure you have imported "reflect-metadata" on top of the main entry file in your application (before any entity imported).If you are using JavaScript instead of TypeScript you must explicitly provide a column type.
port-of-mars-nuxt-1  |     at /code/web/node_modules/typeorm/decorator/columns/Column.js:52:23
port-of-mars-nuxt-1  |     at __decorateClass$6 (file:///code/web/.nuxt/dev/index.mjs:532:24)
port-of-mars-nuxt-1  |     at file:///code/web/.nuxt/dev/index.mjs:542:1
port-of-mars-nuxt-1  |     at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
port-of-mars-nuxt-1  |     at async Promise.all (index 0)
port-of-mars-nuxt-1  |     at async ESMLoader.import (node:internal/modules/esm/loader:533:24)
port-of-mars-nuxt-1  |     at async loadESM (node:internal/process/esm_loader:91:5)
port-of-mars-nuxt-1  |     at async handleMainPromise (node:internal/modules/run_main:65:12)
```

**Comment by alee** [comment]
related issue: https://github.com/evanw/esbuild/issues/257

**Comment by alee** [comment]
closing for now until we decide on #795
